### ISSUE TITLE
ndf parser that might be of use for you.

### ISSUE THREAD

**Issue by Ulibos** [BE3dARt/WARNO-DATA#11]
Hi! Sorry for contacting you via Issues, wasn't able to find any other means. I've recently released a [parser](https://github.com/Ulibos/ndf-parse) that converts Eugen's ndf files to python structures, allows for reading and editing data as well as writing it back as an ndf code. But you might be interested in the first part of that statement - reading data in. Since it's aware of the data structure, you don't have to weave a bunch of regexps together to get to a specific item. Potentially it would make your scripts substantially shorter and easier to maintain. Here is an example code for your case:

```py
import ndf_parse as ndf

# Setup path to the source mod. Leaving output mod empty since you don't need to write data out
mod = ndf.Mod(r"path\to\mod\root", "") 
ammo = mod.parse_src(r"GameData\Generated\Gameplay\Gfx\Ammunition.ndf")
for obj_row in ammo:
    obj = obj_row.value  # row stores additional metadata like namespace, visibility, type etc. Value stores well... the value
    # skip anything that is not of this type
    if obj.type != "TAmmunitionDescriptor": 
        continue
    name = obj.by_member("Name").value 
    caliber = obj.by_member("Caliber").value
    ...
```

You can take a look at the [documentation](https://ulibos.github.io/ndf-parse/pages/docs.html) to see some code examples and an API reference. Hope this helps and again sorry for the issue format!

**Comment by m1rza-s** [comment]
Thanks man, but I already died on that hill. Now I have my own horrible code that does something similar.

**Comment by Perytron** [comment]
Thank you very much for bringing your .ndf parser to my attention. ❤️ It might be very useful to me indeed. 
I haven't got time to further proceed with this project as I need to get done some other things first. Nevertheless, I intend to revisit it during the week after next. I will see how (or if) I can integrate your .ndf parser into my work. 
Thanks again for sharing it with me! 😄

**Comment by Ulibos** [comment]
I was told you are present in the official Eugen discord. In case you have any questions regarding the tool, feel free to ping me there for quick clarifications and help.

**Comment by Perytron** [comment]
This repository has transitioned into a dedicated wiki, as detailed in [this pull request](https://github.com/Perytron/WARNO-DATA/pull/13). However, I will ensure that your parser is included in the wiki, making it available for others who may need one.
